### ISSUE TITLE
Security vulnerability coming from `diff`

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/nodeunit-x#2]
```
`-- grunt-contrib-nodeunit@2.0.0
  `-- nodeunit-x@0.12.2
    `-- tap@12.7.0
      +-- tap-mocha-reporter@3.0.9
      | `-- diff@1.4.0
      `-- ts-node@8.2.0
        `-- diff@4.0.1
```

[WS-2018-0590](https://github.com/kpdecker/jsdiff/commit/2aec4298639bf30fb88a00b356bf404d3551b8c0)
Vulnerable versions: < 3.5.0
Patched version: 3.5.0

A vulnerability was found in diff before v3.5.0, the affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) attacks.

Maybe it's not valid, not sure, it comes from GitHub security alerts

**Comment by XhmikosR** [comment]
@vladikoff: adding a lock file does not fix the issue. Diff needs to be updated for this to be fixed...

**Comment by vladikoff** [comment]
I ran the audit and it didn't show anything, hrmmm

**Comment by XhmikosR** [comment]
This vulnerability is from GitHub, not from npm audit.

**Comment by XhmikosR** [comment]
If you update versions and stuff, you should also switch to the caret operator. Using `>=` is dangerous IMO even for devDependencies.
