### ISSUE TITLE
Update tap

### ISSUE THREAD

**Issue by parasyte** [gruntjs/nodeunit-x#7]
`tap` 0.14 includes a transitive dependency on a vulnerable version of `lodash` that produces a lot of warnings in `npm audit`.

**Comment by XhmikosR** [comment]
@vladikoff could you take care of this please? Not sure if it's fixed in tap v15, just keep in mind to make it a minor version here since it's currently on 0.x and then a major one in grunt-contrib-nodeunit.

**Comment by vladikoff** [comment]
Done! thanks for the note!

**Comment by XhmikosR** [comment]
Perfect, thanks!
